language: rust
sudo: required
cache: cargo
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
rust:
  - nightly
  - beta
  - stable

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin -f
  fi

script:
- cargo clean
- cargo build --features serde
- cargo test --features serde


after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
